# The doctors can manage their patients' measurements from their hospital's network during office hours

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ex: <http://example.com/>
PREFIX sm: <http://sm.example.com#>
PREFIX int: <http://int.example.com#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX sp: <http://spin.com#>

ASK
WHERE {
	?v9 sm:has_doctor ?r;
      sm:from         ?v22;
	  sm:to           ?v23;
	  sm:for_patient  ?v11.
	?sensor sm:owner  ?v11.
	BIND (xsd:date('2017-09-12') as ?v24).
	FILTER (xsd:date(?v22) < ?v24 && xsd:date(?v23)>?v24)
}